from setuptools import find_packages, setup


setup(
    name="graphifyy",
    version="0.4.23",
    description="AI coding assistant skill (Claude Code, Codex, OpenCode, Cursor, Gemini CLI, Aider, OpenClaw, Factory Droid, Trae, Hermes, Kiro, Google Antigravity) - turn any folder of code, docs, papers, images, or videos into a queryable knowledge graph",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    license="MIT",
    python_requires=">=3.10",
    packages=find_packages(include=["graphify*"]),
    include_package_data=True,
    package_data={
        "graphify": [
            "skill.md",
            "skill-codex.md",
            "skill-opencode.md",
            "skill-aider.md",
            "skill-copilot.md",
            "skill-claw.md",
            "skill-windows.md",
            "skill-droid.md",
            "skill-trae.md",
            "skill-kiro.md",
            "skill-vscode.md",
            "skill-qwen.md",
        ]
    },
    install_requires=[
        "networkx",
        "tree-sitter>=0.23.0",
        "tree-sitter-python",
        "tree-sitter-javascript",
        "tree-sitter-typescript",
        "tree-sitter-go",
        "tree-sitter-rust",
        "tree-sitter-java",
        "tree-sitter-c",
        "tree-sitter-cpp",
        "tree-sitter-ruby",
        "tree-sitter-c-sharp",
        "tree-sitter-kotlin",
        "tree-sitter-scala",
        "tree-sitter-php",
        "tree-sitter-swift",
        "tree-sitter-lua",
        "tree-sitter-zig",
        "tree-sitter-powershell",
        "tree-sitter-elixir",
        "tree-sitter-objc",
        "tree-sitter-julia",
        "tree-sitter-verilog",
    ],
    extras_require={
        "mcp": ["mcp"],
        "neo4j": ["neo4j"],
        "pdf": ["pypdf", "html2text"],
        "watch": ["watchdog"],
        "svg": ["matplotlib"],
        "leiden": ["graspologic; python_version < '3.13'"],
        "office": ["python-docx", "openpyxl"],
        "video": ["faster-whisper", "yt-dlp"],
        "all": [
            "mcp",
            "neo4j",
            "pypdf",
            "html2text",
            "watchdog",
            "graspologic; python_version < '3.13'",
            "python-docx",
            "openpyxl",
            "faster-whisper",
            "yt-dlp",
            "matplotlib",
        ],
    },
    entry_points={
        "console_scripts": [
            "graphify=graphify.__main__:main",
        ]
    },
)
